name: C Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: make setup
      - name: run linter
        run: make lint
      - name: run tests
        run: make test
      - name: compile
        run: make
