name: C Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install build tools
        run: sudo scripts/install-build-tools.sh
      - name: install dependencies
        run: sudo scripts/install-dependencies.sh
      - name: run linter
        run: make lint
      - name: compile
        run: make
